---
title: "bernardo"
author: "Andrew Simpkin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
library(tidyverse)
library(stringdist)
library(stringi)
library(cleanNLP)
library(jsonlite)
})

options(dplyr.summarise.inform = FALSE)
options(width = 120)
theme_set(theme_minimal())
cnlp_init_udpipe()
```


```{r}
###############################################################
# JSON=>CSV

jtext <- read_lines("celva.sp_full_dataset.json")
#jtext <- read_lines("../data/selva_full_dataset(3).json")
jtext <- stri_replace_all(jtext, "null", fixed = "NaN")
jd <- jsonlite::fromJSON(jtext)

df <- vector('list', length(jd))
for (j in seq_along(jd)){
  z <- jd[[j]]
  mods <- z$predictions$models
  temp <- bind_rows(mods$predictions)
  temp$model <- rep(mods$model_name, each = 3)
  temp$rank <- rep(1:3, 3)  
  for (nom in names(jd[[j]]$metadata))
  {
    temp[[nom]] <- jd[[j]]$metadata[[nom]]
  }
  temp$name <- names(jd)[j]
  temp$maskedToken_token_str <- z$predictions$maskedToken$token_str
  temp$maskedToken_ud_pos <- z$predictions$maskedToken$ud_pos
  temp$maskedSentenceStr <- z$predictions$maskedSentenceStr
  temp$maskedTokenIdx <- z$predictions$maskedTokenIdx
  temp$maskedTokenStr <- z$predictions$maskedTokenStr
  df[[j]] <- as_tibble(temp)
}
df <- bind_rows(df)
df <- select(df, name, everything())

# addinc a success variable when the token has been predicted by the LLM
df$success <- as.numeric(df$token_str == df$maskedTokenStr)
```

```{r}
failed = df %>% filter(success == 0 & rank == 1 & model == "../models/bert-base-uncased-fullefcamdat/") %>%
  select(model, rank, success, score)


failed %>% ggplot(aes(x=score)) + geom_density()

# Select number of clusters
k <- 3
set.seed(12345)
# Build model with k clusters
km.out <- kmeans(failed$score, centers = 2)

library(factoextra)
failed$cluster <- factor(km.out$cluster)

failed %>%
  na.omit() %>%
  ggplot(aes(x=cluster, y = score, fill = cluster)) + 
  geom_boxplot(varwidth = FALSE) + theme_bw() + 
  theme(axis.text.x = element_text(angle = 0, hjust=1)) + 
  labs(title = "Prob by clusters", x ="Predicted prob",fill = "Cluster")

```

# Plot the probabilities for candidates (success and failed)
```{r}

df %>%
  mutate(rank = as.factor(rank)) %>%
  ggplot(aes(fill = rank, x = score)) + 
  geom_density(alpha = 0.5) + theme_bw() + 
  facet_wrap(~model)

df %>%
  filter(model == "../models/bert-base-uncased-fullefcamdat/" & rank == 1) %>%
  mutate(rank = as.factor(rank)) %>%
  ggplot(aes(fill = rank, x = score)) + 
  geom_density(alpha = 0.5) + theme_bw() + 
  facet_wrap(~ud_pos)

```

# Plot the probabilities for successful candidates by rank

```{r}

df %>%
  mutate(rank = as.factor(rank)) %>%
  filter(success == 1) %>%
  ggplot(aes(fill = rank, x = score)) + 
  geom_density(alpha = 0.5) + theme_bw() + 
  facet_wrap(~model)

```


# Plot the probabilities for successful candidates, including 0 if none

```{r}

df %>%
  mutate(rank = as.factor(rank)) %>%
  filter(success == 1) %>%
  ggplot(aes(x = score)) + 
  geom_density(alpha = 0.5) + theme_bw() + 
  facet_wrap(~model)

```


```{r}
# some analyses--------

# success rate of predicting the masked token
df |>
  filter(ud_pos == "ADP") |>
  group_by(model, rank) |>
  summarize(success_rate = mean(success),
            score_mean = mean(score)) %>%
  select(model, success_rate, score_mean, rank)

# success rate of predicting the masked token
df |>
  group_by(model, rank) |>
  summarize(success_rate = mean(success))

# distinct average probabilities of the model predictions according to rank
df |>
  group_by(model, rank, success) |>
  summarize(score_mean = mean(score)) 


# probabilities per UPOS categories for successful predictions
df |>
  group_by(model, rank, ud_pos, success) |>
  summarize(score_mean = mean(score)) |>
  filter(rank == 1, success == 1) |>
  arrange(model, score_mean) |>
  print(n = Inf)


# corresponding support (n) of probabilities per UPOS categories for successful predictions 
df |>
  group_by(model, rank, ud_pos) |>
  summarize(success_rate = mean(success), n = n()) |>
  filter(rank == 1) |>
  arrange(model, success_rate) |>
  print(n = Inf)


#
df |>
  group_by(name, model, success) |>
  summarize(score_sum = sum(score))  


#maybe use dispersion....
df |>
  group_by(name, model) |>
  filter(rank <= 2) |>
  reframe(score, lag(score))
#  summarize(score, lag(score))




```

